[package]
authors = ["Paul <paul@paul-mayer.eu>"]
edition = "2018"
name = "hello-rust"
version = "0.1.0"

[dependencies]
actix-web = "3"
async-graphql = "2.0"
async-graphql-actix-web = "2.0"
serde_json = "1.0"
futures = "0.3"
async-std = { version = "1", features = ["attributes"] }
